PortalWeb/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortalWeb.Data;
using PortalWeb.Models;

namespace PortalWeb.Controllers
{
    public class AppsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AppsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Apps
        public async Task<IActionResult> Index(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                var applicationDbContext2 = _context.Apps.Where(s => s.Name == searchString || s.Secret == searchString || s.TagLine == searchString || s.User.UserName == searchString).Include(a => a.User);
                return View(await applicationDbContext2.ToListAsync());
            }

            var applicationDbContext = _context.Apps.Include(a => a.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Apps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Apps == null)
            {
                return NotFound();
            }

            var app = await _context.Apps
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (app == null)
            {
                return NotFound();
            }

            return View(app);
        }

        // GET: Apps/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName");
            return View();
        }

        // POST: Apps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Secret,UserId,Name,TagLine,LogoUrl,RedirectUrl")] App app)
        {
            if (ModelState.IsValid)
            {
                _context.Add(app);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {
                    ModelState.AddModelError("error", "This Secret Is Used Before , Please Use Another One");
                    return View(app);
                }
                return RedirectToAction(nameof(Index));

            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", app.UserId);
            return View(app);
        }

        // GET: Apps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Apps == null)
            {
                return NotFound();
            }

            var app = await _context.Apps.FindAsync(id);
            if (app == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "I", app.UserId);
            return View(app);
        }

        // POST: Apps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Secret,UserId,Name,TagLine,LogoUrl,RedirectUrl")] App app)
        {
            if (id != app.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(app);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppExists(app.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", app.UserId);
            return View(app);
        }

        // GET: Apps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Apps == null)
            {
                return NotFound();
            }

            var app = await _context.Apps
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (app == null)
            {
                return NotFound();
            }

            return View(app);
        }

        // POST: Apps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Apps == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Apps'  is null.");
            }
            var app = await _context.Apps.FindAsync(id);
            if (app != null)
            {
                _context.Apps.Remove(app);
            }
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException /* ex */)
            {
                ModelState.AddModelError("error", "This Is Used By Another Entity Soo You Can't Delete It");
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool AppExists(int id)
        {
            return (_context.Apps?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PortalWeb/Views/Apps/Create.cshtml
@model PortalWeb.Models.App

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>App</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Secret" class="control-label"></label>
                <input asp-for="Secret" class="form-control" />
                <span asp-validation-for="Secret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TagLine" class="control-label"></label>
                <input asp-for="TagLine" class="form-control" />
                <span asp-validation-for="TagLine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoUrl" class="control-label"></label>
                <input asp-for="LogoUrl" class="form-control" />
                <span asp-validation-for="LogoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RedirectUrl" class="control-label"></label>
                <input asp-for="RedirectUrl" class="form-control" />
                <span asp-validation-for="RedirectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PortalWeb/Views/Apps/Delete.cshtml
@model PortalWeb.Models.App

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>

    <h4>App</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Secret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Secret)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TagLine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TagLine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LogoUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LogoUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RedirectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RedirectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PortalWeb/Views/Apps/Details.cshtml
@model PortalWeb.Models.App

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>App</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Secret)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Secret)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TagLine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TagLine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LogoUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LogoUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RedirectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RedirectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PortalWeb/Views/Apps/Edit.cshtml
@model PortalWeb.Models.App

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>App</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Secret" class="control-label"></label>
                <input asp-for="Secret" class="form-control" />
                <span asp-validation-for="Secret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TagLine" class="control-label"></label>
                <input asp-for="TagLine" class="form-control" />
                <span asp-validation-for="TagLine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoUrl" class="control-label"></label>
                <input asp-for="LogoUrl" class="form-control" />
                <span asp-validation-for="LogoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RedirectUrl" class="control-label"></label>
                <input asp-for="RedirectUrl" class="form-control" />
                <span asp-validation-for="RedirectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PortalWeb/Views/Apps/Index.cshtml
@model IEnumerable<PortalWeb.Models.App>

@{
    ViewData["Title"] = "Index";
}
<div class="container">
<h1>Index</h1>

<p>
    <a class="btn btn-primary float-end" asp-action="Create">Create New</a>
</p>
    <form asp-controller="Apps" asp-action="Index">
        <p>
            Title: <input type="text" name="SearchString" />
            <input type="submit" value="Filter" />
        </p>
    </form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Secret)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TagLine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LogoUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RedirectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.Secret)
            </td>
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.TagLine)
            </td>
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.LogoUrl)
            </td>
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.RedirectUrl)
            </td >
                <td class="w-10">
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
                <td class="w-40">
                    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>